name: Release

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build Patches
        run: ./gradlew generatePatchesFiles

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: patches-${{ github.sha }}
          path: |
            build/libs/*.jar
            build/outputs/**/*

  release:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: patches-${{ github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE_TOKEN }}
        run: npx semantic-release

  trigger-apk-build:
    name: Trigger APK Build
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow
        uses: convictional/trigger-workflow-and-wait@v1
        with:
          owner: crimera
          repo: piko-builds
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: build-apk.yml
          wait_workflow: true
          wait_workflow_timeout: 600
